\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename geni-ar.info
@settitle The GENI Account Request System

@c indent the first paragraphs like the others
@firstparagraphindent insert
@c %**end of header

@include version.texi

@c combine the program index into the concept index
@syncodeindex pg cp

@copying
Copyright @copyright{} 2016 Raytheon BBN Technologies

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and/or hardware specification (the ``Work'') to
deal in the Work without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Work, and to permit persons to whom the Work
is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Work.

THE WORK IS PROVIDED ``AS IS'', WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS
IN THE WORK.
@end copying

@titlepage
@title The GENI Account Request System
@subtitle Version @value{VERSION}
@subtitle @value{UPDATED-MONTH}
@author Tom Mitchell
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top
@top GENI Account Requests

@insertcopying
@end ifnottex

@menu
* Introduction::    Introduction.
* Installation::     Installation.
* Operations::       Operator's guide.
* System Administration:: Administrator's guide.
* Index::            Complete index.
@end menu


@node Introduction
@chapter Introduction

@cindex introduction
@cindex PHP

The GENI Account Request system allows GENI users to request accounts
on the GENI identity provider and to recover or change their passwords.

@node Installation
@chapter Installation

@cindex installation

The installation guide is provided with the source distribution in the
file @code{INSTALL.md}. Additional installation guides are also included
in the source distribution for installation and configuration of software
dependencies like Shibboleth and LDAP. Please see the source distribution
for complete installation instructions.

Installation is currently only supported on CentOS 7. It should be possible
to port the software to other Linux distributions like Ubuntu.


@node Operations
@chapter Operations

@section Handling Account Requests

Operators are notified by email when an account request has
been confirmed by the requester.
The email notification has an approve link to an expedited approval
page. This link can be used if the account request contains enough
information to approve it. The email notification contains a second
link to allow the operator to access the full account request system
to handle the request in a variety of ways.

When an account request arrives, it should:

@itemize
@item contain a school or company email address. The use of public email
systems like GMail, HotMail, qq.com, Yahoo, etc. is discouraged.
@item contain a recognizable organization, usually a school or company
name. Organizations like `organization' or similar are discouraged.
@item contain a reasonable reason for using GENI. Sometimes when a
classroom of students is requesting access they don't know what to enter,
so flexibility on this field is advisable. But in normal cases, look
for a reasonable research purpose.
@item contain a first and last name. Sometimes students get clever and
enter an obviously fake name like `spongebob' or `32'. These account
requests should be denied.
@end itemize

Typically we write back to requesters for the following reasons:

@enumerate
@item They have used a public or anonymous email service
@item Their organization is wrong or cannot be found
@item Their reason for using GENI is too vague or unclear
@item Their school or company does not already have a project lead
@end enumerate

@section Operator Tabs

The user interface is divided into tabs. Each tab
displays requests in that state. For instance the ``Email Confirmed''
tab displays account requests that have had their email address
confirmed, but have not been processed by an operator. The use and purpose
of each tab is explained below.

@float Figure,fig:operatorTabs
@c Note: do not include the image extension, it gets figured out
@c       automatically. This uses UI.png for the image.
@image{UI,6in}
@caption{Operator tabs}
@end float

@cindex Email Confirmed
@cindex Tabs, Email Confirmed
@subsection Email Confirmed

This tab displays account requests that have had their email address
confirmed by the requester. Requests on this tab have not yet been
processed by an operator.
Each request in the ``Email Confirmed'' state should be processed by
an operator using the dropdown menu. Here is what each option will
do for account requests:

If the request looks good, it can
be approved using the ``Approve'' option. If more information is needed
from the requester, an email can be sent using the ``Email Requester''
option. If the GENI Project Leads should be consulted about the request
they can be contacted using the ``Email Leads'' option.

@cindex Waiting for Confirmation
@cindex Tabs, Waiting for Confirmation
@subsection Waiting for Confirmation

Requests on the @samp{Waiting for Confirmation} tab have not yet been confirmed
by the requester. An email is automatically sent when an account
request is received. If a request stays in this state for a week or more
it is likely that:

@itemize
@item The email went to the requester's junk email folder
@item The requester mistyped their email address
@item The requester changed their mind about wanting a GENI account
@end itemize

This tab can be useful when researching the state of an account
request. Sometimes a requester will ask why their request has not
been processed. It may be that it is stuck waiting for their confirmation.
If that is the case, verify that the email address is correct on the
account request. If it is not, ask the requester to submit a new
account request with the correct email address.

In general, no action is required by operators for account requests
on this tab.

@cindex Waiting for Leads
@cindex Tabs, Waiting for Leads
@subsection Waiting for Leads

Account reqeusts on the @samp{Waiting for Leads} tab are pending
input from the GENI Project Leads. An operator has used the
@samp{Email Leads} option to ask the leads for their input.

@xref{Email Leads}.

@cindex Waiting for Requester Response
@cindex Tabs, Waiting for Requester Response
@subsection Waiting for Requester Response

Account requests listed on this tab are pending further input from the
requester. An operator has used the @samp{Email Requester} option to
contact the requester to request additional information. If a user
writes back with more information, the account request can be
approved or denied from here. It is also possible to use the
@samp{Email Requester} option again to email the requester for more
information.

@xref{Email Requester}.

@cindex Approved Reqs
@cindex Tabs, Approved Reqs
@subsection Approved Reqs

The @samp{Approved Reqs} tab lists all the account requests that
have been approved and are active. No action can be taken on these
account requests because they have already been processed. This
tab can be used to see if there are other existing accounts for
this school or company.

@cindex Denied Reqs
@cindex Tabs, Denied Reqs
@subsection Denied Reqs

The @samp{Denied Reqs} tab lists all the account requests that have been
denied. This tab can be useful to locate previous requests from a
requester who is particularly persistent.

@section Account Request Handling Options

Account Requests are displayed with a drop-down menu of applicable
options for handling the request. At each stage in the processing,
until a request is ultimately approved or denied, this drop-down
menu will appear.

@cindex Approve
@cindex Options, Approve
@subsection Approve
Approves the account request and emails the requester a standard email
explaining how to use their account.

After approval the request will appear on the ``Approved Reqs'' tab.

@anchor{Email Requester}
@cindex Email Requester
@cindex Options, Email Requester
@subsection Email Requester
Takes the operator to a page containing a template email. The operator
can edit the email before it is sent. The email is sent to the requester
with the @samp{Reply-To} field set to @email{help@@geni.net} so
that the requester can reply with additional information or questions.

After emailing the requester, the request will apear on the ``Waiting
for Requester Response'' tab.

@anchor{Email Leads}
@cindex Email Leads
@cindex Options, Email Leads
@subsection Email Leads
Takes the operator to a page containing a template email. The operator
can edit the email before it is sent. The email is sent to the
GENI Project Leads
with the @samp{Reply-To} field set to @email{help@@geni.net}.
This option is typically used to ask the leads if a request should be
approved or if they require additional information before making a
decision.

After emailing the leads, the request will appear on the ``Waiting for Leads''
tab.

@cindex Add Note
@cindex Options, Add Note
@subsection Add Note

It is sometimes useful to attach a note to an account request. This can
remind an operator of something later, or server to communicate information
to other operators. For instance, if a requester's school does not yet
have a project lead and they are asked to find one, it can be useful
to add a note saying, ``waiting for project lead'' so operators know they
should not approve the request until there is a project lead for this
requester.

After adding a note to a request the note is visible to the far right
of the account request. Scroll right to see it.

@cindex Deny
@cindex Options, Deny
@subsection Deny

If it is determined that a requester should not be granted a request,
the request should be denied using the @samp{Deny} option. Denying a
request cannot be undone by the web UI.

After denying a request the request will appear on the
@samp{Denied Reqs} tab.

@cindex Confirm Requester
@cindex Options, Confirm Requester
@subsection Confirm Requester
This option is obsolete. Please do not use ``Confirm Requester''.

@cindex whitelist
@section Email Domain Whitelist

@emph{The email domain whitelist will be described in the future.}

@section Example Requests
@subsection Example Request 1

This is a de-identified version of an actual account request.

@example

first_name: alfred
last_name: neuman
email: alfredneuman98@@gmail.com
organization: testoncloud
title: Linux Admin
reason: Tesing about cloud.

@end example

This account request lacks several pieces of important information:
@enumerate
@item A school or business email address
@item A valid organization
@item A clear reason for using GENI
@item Possibly a project lead, but there is too little information to know
@end enumerate

Here is a reply to this applicant which enumerates the things they need
to do to get a GENI account:

@example

Dear alfred,

Thank you for your interest in GENI. In order to grant access we
will need additional information:

1. Please submit a new account request using your school or
   work email address. If for some reason you are unable to do
   this, please write us back to explain the circumstances.

2. Please enter your school or company name in the organization field

3. Please provide more information about your proposed use of GENI.
   ``Tesing about cloud'' is too vague.

3. Please be aware that all research on GENI happens in a project.
   If you do not qualify as a GENI project lead you will need a GENI
   project lead at your school or company who can oversee your work.
   More information about GENI project leads is available at
   http://groups.geni.net/geni/wiki/GENIConcepts

Thanks,
The GENI Project Office

@end example

@subsection Example Request 2

This is a de-identified version of an actual account request. This is a very
common type of request. It appears to be a student at a University who
wants to use GENI for academic work. The only question is whether the
University already has a project lead to create a project for this user.

How do you determine if a University already has users?

How do you know if there is a project lead at a University?

@example

first_name: Alfred
last_name: Neuman
email: aneuman1@@example.edu
organization: Example University
title: Video transmission in software defined networking
reason: I would like to test the behavior that has streaming
        video from a CCTV camera on a network sdn

@end example

Looks good. If this is a new University, they will need a project lead.

How to tell if this is a new University? Click on the ``Approved Reqs'' tab.
Then use the ``Search:'' box to type in the university email address
(``example.edu''). If there are already accounts for this university or
company they will show up in the search.

@example

Dear Alfred,

Thank you for your interest in GENI. In order to get an account you
need to have a GENI project lead at your school. Perhaps your advisor
is a good person to ask. Have them request a GENI account. Once we
have a professor at your school approved as a GENI project lead, we
will be able to approve your account so that you can use GENI.

More information about GENI Project Leads is available at
http://groups.geni.net/geni/wiki/GENIConcepts.

Thanks,
The GENI Project Office

@end example

@subsection Example Request 2

@example

first_name: Alfred
last_name: Neuman
email: neumy97@@hotmail.com
organization: University of Illnois at Urbana Champaign
title: Student Researcher
reason: Research

@end example

Things to note:
@enumerate
@item email is an anonymous mail service, hotmail
@item organization is a US institution that may be a member of InCommon
@end enumerate

Where to check for InCommon membership?

Just because they're in InCommon doesn't mean they don't need an account.
Search for existing accounts from the same school, or search on the portal
for existing accounts where the eppn is from the school, not the GENI IdP.


@node System Administration
@chapter System Administration

@section Introduction

@emph{This section unintentionally left blank.}

@section @code{cron} jobs
@cindex cron

@subsection Expired account notifications
GENI IdP accounts can have an expiration date. Tutorial accounts
in particular will have an expiration, generally a couple days after
the tutorial ends. This expiration is not enforced; rather,
after this time the administrator should properly disable
and delete the account. This cron entry detects IdP accounts
that are active but expired, and emails the administrators
of the expired usernames. The administrator should then
remove that account from any GENI Clearinghouse projects and
disable the account in the MA, and then Delete the account
at the GENI IdP.

@example
# Email admins the usernames of any expired but active IdP accounts
0 1 * * 1,2,3,4,5 * /usr/local/sbin/geni-ar-expired-accounts
@end example


@section Log files

@subsection Apache log file
@cindex log files
@cindex Apache

@emph{This section unintentionally left blank.}

@node Index
@unnumbered Index

@printindex cp

@bye
